apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tududi.secretName" . }}
  labels:
    {{- include "tududi.labels" . | nindent 4 }}
type: Opaque
stringData:
  TUDUDI_USER_EMAIL: {{ .Values.tududi.user.email | quote }}
  TUDUDI_USER_PASSWORD: {{ .Values.tududi.user.password | quote }}
  TUDUDI_SESSION_SECRET: {{ .Values.tududi.sessionSecret | quote }}
  {{- if .Values.tududi.telegram.enabled }}
  TUDUDI_TELEGRAM_BOT_TOKEN: {{ .Values.tududi.telegram.botToken | quote }}
  {{- end }}
