# config/database.yml
default: &default
  adapter: sqlite3
  pool: 15
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: tududi_db/production.sqlite3
